global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "backend-app"
    metrics_path: "/api/metrics"
    static_configs:
      - targets: ["host.docker.internal:4000"] # backend on host

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["node_exporter:9100"]
